steps:
  - retriever:
      name: embedding
      model_name: intfloat/multilingual-e5-large
      top_k: 0.8
      cache: ./cache/multilingual-e5-large-metadata
      use_post: False
      dataset:
        name: multiclaim_metadata
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: original
        use_metadata: True
  - retriever:
      name: embedding
      model_name: intfloat/multilingual-e5-large
      top_k: 100
      cache: ./cache/multilingual-e5-large-metadata
      use_post: True
      dataset:
        name: retrieved_documents
  - postprocessor:
      name: retriever_postprocess