steps:
  - retriever:
      name: faiss
      model_name: all-MiniLM-L12-v2
      top_k: 100
      cache: ./cache/all-MiniLM-L12-v2
      use_post: True
      dataset:
        name: multiclaim
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: english
  - postprocessor:
      name: retriever_postprocess