steps:
  - retriever:
      name: faiss
      model_name: BAAI/bge-m3
      top_k: 100
      cache: ./cache/bge-m3
      use_post: True
      dataset:
        name: multiclaim
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: original
  - postprocessor:
      name: retriever_postprocess