steps:
  - retriever:
      name: faiss
      model_name: gtr-t5-large
      top_k: 100
      cache: ./cache/gtr-t5-large
      use_post: True
      dataset:
        name: multiclaim
        crosslingual: False
        fact_check_language: None
        language: None
        post_language: None
        split: None
        version: english
  - postprocessor:
      name: retriever_postprocess